# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 2e828315b8e34a9f4c12ac9249b55daf3482ac840265186e5ccb5fc8c6a9f4370eb9c6be8336712c04fbfce5f4b14760466e248ccfcfa3b30ed55589110e2c11

test:
  secret_key_base: 5a23e4882f4935b070ac903d082d04b73004f51e24cc2ae9ff179806092eece50d69617feae2d97aed193c9b9e5946f6fb1a5871aac38372e56376d5fca21dc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
